development:
  adapter: postgresql
  database: garden_share_development
  pool: 5
  timeout: 5000

test:
  adapter: postgresql
  database: garden_share_test
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  database: garden_share_production
  pool: 5
  timeout: 5000
