gardens = Garden.create([
          { address: "3030 Linden Street", 
            city: "Oakland", 
            garden_description: "Ad vis denique adipisci iudicabit. Quidam eleifend suavitate sea no. Est eligendi antiopam ad. An est idque senserit honestatis, ad mea purto vero deserunt. Vim ea brute graece adolescens.", 
            relationship_desired: "Hinc libris mandamus usu ad, duo mutat explicari ex. Noluisse gloriatur consetetur id sed, sit in partem vidisse, ei sea reque illum."},
          { address: "659 59th Street", 
            city: "Oakland", 
            garden_description: "At nam atqui omnium consequat, ea autem consul assentior vis, habeo nominavi vituperatoribus ne vis. Ex vel congue docendi, mei dicant aperiri scaevola te.", 
            relationship_desired: "No bonorum volutpat usu, sit ea singulis adversarium deterruisset, nam et dicit eripuit. Diceret saperet tibique ne est, sed ne alii modus scribentur, mei ex tempor accumsan."},
          { address: "1024 63rd Street", 
            city: "Oakland", 
            garden_description: "An scripta labores duo, pro te expetenda salutatus elaboraret, discere dignissim sed te.", 
            relationship_desired: "Usu ullum delenit suavitate ad, eu elit virtute pro. Eu paulo graeci has, ius harum audiam voluptaria ei."},
          { address: "5424 Genoa Street", 
            city: "Oakland", 
            garden_description: "Everti accommodare eam ne, natum veniam consetetur has ne. Eius dicam deseruisse no cum.", 
            relationship_desired: "Te eos deserunt assentior signiferumque, no ferri consequuntur pro. Brute velit graecis cu sed, usu ea hinc discere petentium."},
          { address: "3315 Chestnut Street", 
            city: "Oakland", 
            garden_description: "Suavitate repudiandae eu sit, ius regione pericula consetetur no. An vocibus fastidii nec, ut vel accusam apeirian.", 
            relationship_desired: "Vix moderatius omittantur ex, zril delectus usu in, quo ei partem electram."},
        ])