gardens = Garden.create([
          { address: "3030 Linden Street",
            neighborhood: "Clawson", 
            city: "Oakland",
            zipcode: "94608",
            geo_location: "37.822158,-122.278915",
            short_description: "Pri autem delenit reprimique ne. Cum iudico assueverit in.",
            description: "Ad vis denique adipisci iudicabit. Quidam eleifend suavitate sea no. Est eligendi antiopam ad. An est idque senserit honestatis, ad mea purto vero deserunt. Vim ea brute graece adolescens.", 
            rules: "Hinc libris mandamus usu ad, duo mutat explicari ex. Noluisse gloriatur consetetur id sed, sit in partem vidisse, ei sea reque illum."},
          { address: "659 59th Street",
            neighborhood: "Upper Telegraph", 
            city: "Oakland",
            zipcode: "94609",
            geo_location: "37.8442729,-122.26697",
            short_description: "Sit at omnis vocent ullamcorper. Pri at fastidii forensibus, eam tota temporibus no.", 
            description: "At nam atqui omnium consequat, ea autem consul assentior vis, habeo nominavi vituperatoribus ne vis. Ex vel congue docendi, mei dicant aperiri scaevola te.", 
            rules: "No bonorum volutpat usu, sit ea singulis adversarium deterruisset, nam et dicit eripuit. Diceret saperet tibique ne est, sed ne alii modus scribentur, mei ex tempor accumsan."},
          { address: "1024 63rd Street",
            neighborhood: "Paradise Park",
            city: "Oakland", 
            zipcode: "94608",
            geo_location: "37.846762,-122.280911",
            short_description: "Consul impedit elaboraret ea vis, mel no admodum volumus suavitate, error noster rationibus est te.", 
            description: "An scripta labores duo, pro te expetenda salutatus elaboraret, discere dignissim sed te.", 
            rules: "Usu ullum delenit suavitate ad, eu elit virtute pro. Eu paulo graeci has, ius harum audiam voluptaria ei."},
          { address: "5424 Genoa Street",
            neighborhood: "Santa Fe", 
            city: "Oakland",
            zipcode: "94608",
            geo_location: "37.839259,-122.2714925",
            short_description: "Eu qui dicat omnesque, mea ne nibh rebum alterum. Ne vide zril latine vix, ex eam wisi democritum efficiendi, te sit idque antiopam.", 
            description: "Everti accommodare eam ne, natum veniam consetetur has ne. Eius dicam deseruisse no cum.", 
            rules: "Te eos deserunt assentior signiferumque, no ferri consequuntur pro. Brute velit graecis cu sed, usu ea hinc discere petentium."},
          { address: "3315 Chestnut Street",
            neighborhood: "Clawson", 
            city: "Oakland",
            zipcode: "94608",
            geo_location: "37.824722,-122.279816",
            short_description: "Te vim enim everti. Sit similique honestatis at. Ei sed brute praesent vulputate.", 
            description: "Suavitate repudiandae eu sit, ius regione pericula consetetur no. An vocibus fastidii nec, ut vel accusam apeirian.", 
            rules: "Vix moderatius omittantur ex, zril delectus usu in, quo ei partem electram."},
          { address: "414 Brannan Street",
            neighborhood: "South of Market", 
            city: "San Francisco",
            zipcode: "94107",
            geo_location: "37.7798936,-122.394879",
            short_description: "Erant philosophia ne usu, id munere tamquam detracto vim, ut wisi habemus maiestatis usu.", 
            description: "Suavitate repudiandae eu sit, ius regione pericula consetetur no. An vocibus fastidii nec, ut vel accusam apeirian.", 
            rules: "Vix moderatius omittantur ex, zril delectus usu in, quo ei partem electram."},
        ])

users = User.create([
          { name: "Riley Eldridge",
            email: "riley@eldridge.com",
            password: "1234567890",
            password_confirmation: "1234567890",
            garden_id: "6" },
          { name: "Payton Pechacek",
            email: "payton@pechacek.com",
            password: "1234567890",
            password_confirmation: "1234567890",
            garden_id: "5" },
          { name: "Payton Pechacek",
            email: "payton@pechacek.com",
            password: "1234567890",
            password_confirmation: "1234567890",
            garden_id: "5" },
          { name: "Florence Harrison",
            email: "florence@harrison.com",
            password: "1234567890",
            password_confirmation: "1234567890",
            garden_id: "4" },
          { name: "Charlie Zeni",
            email: "charlie@zeni.com",
            password: "1234567890",
            password_confirmation: "1234567890",
            garden_id: "3" },
          { name: "Jewel Anholts",
            email: "jewel@anholts.com",
            password: "1234567890",
            password_confirmation: "1234567890",
            garden_id: "2" },
          { name: "Casey Victore",
            email: "casey@victore.com",
            password: "1234567890",
            password_confirmation: "1234567890",
            garden_id: "1" },     
        ])